### ISSUE TITLE
Minimum instances

### ISSUE THREAD

**Issue by FSchmidt-FUNKE** [cloudfoundry/app-autoscaler-cli-plugin#95]
Hi everyone :)

I'm pretty to Foundry and the Autoscaler and I would like to set the minimum number of instances to 0. I want to make sure, that the service is only running, when it has throughput.
I can remove all running instances of a service manually and then scale it back up to one with the help of the autoscaler, but I can't manage to go back to zero instances. I think it might be because I can't set the min_instaces to 0.

**Comment by joergdw** [comment]
Hi there!

We plan to support this use-case in the future but currently we do not support downscaling to zero. Probably you have manually started an instance when you were on zero instances?! Autoscaler needs metrics to act in dependency on their values. But it does not get any metric when you are on zero instances and consequently is expected to do nothing at all.

Kind regards!

**Comment by joergdw** [comment]
It is unexpected by us that Autoscaler scales up from 0 instances. That's interesting. Could you please check that by looking into the scaling-history of Autoscaler? Do you see the particular upscaling-event that has scaled up from 0 to 1 instance?

**Comment by FSchmidt-FUNKE** [comment]
There is an [event](https://imageupload.io/3lhkrtV5ESyIydv), which shows that I upscale from 0 to 1.

**Comment by joergdw** [comment]
It looks to me that this issue is now solved. But if you want to have a ticket open for this scaling-to-zero-feature, you may open a feature-request-ticket on the main repository on <https://github.com/cloudfoundry/app-autoscaler-release>. There has been already some contact to others wishing the same feature. But as I stated above it is quite low on our priority-list and this may take quite some time before we start it.
